name: Website Uptime Monitor

on:
  schedule:
    - cron: "* * * * *"  # Runs every minute
  workflow_dispatch: null

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Check uptime of the URL
        uses: srt32/uptime@v0.2
        id: uptime_check
        with:
          url-to-hit: https://www.google.com
          expected-statuses: "200"
      
      - name: Send Email Report
        if: always()
        run: |
          # Install necessary packages for sending email
          sudo apt-get install -y msmtp jq

          # Set Gmail credentials from GitHub secrets
          GMAIL_USERNAME=${{ secrets.GMAIL_USERNAME }}
          GMAIL_PASSWORD=${{ secrets.GMAIL_PASSWORD }}
          TO_EMAIL="ktharun4456@gmail.com"  # Replace with your recipient's email address
          SUBJECT="Website Uptime Report"

          # Get the status code from the previous step
          STATUS_CODE=${{ steps.uptime_check.outputs.status_code }}

          # If the status code matches, the website is up, else it's down
          if [ "$STATUS_CODE" == "200" ]; then
            BODY="The website https://www.google.com is UP. Status code: 200."
          else
            BODY="The website https://www.google.com is DOWN. Status code: $STATUS_CODE."
          fi

          # Configure msmtp to send the email via Gmail SMTP
          echo "account default" > ~/.msmtprc
          echo "host smtp.gmail.com" >> ~/.msmtprc
          echo "port 587" >> ~/.msmtprc
          echo "from $GMAIL_USERNAME" >> ~/.msmtprc
          echo "auth on" >> ~/.msmtprc
          echo "user $GMAIL_USERNAME" >> ~/.msmtprc
          echo "password $GMAIL_PASSWORD" >> ~/.msmtprc
          echo "tls on" >> ~/.msmtprc
          echo "tls_starttls on" >> ~/.msmtprc
          echo "logfile ~/.msmtp.log" >> ~/.msmtprc

          # Ensure that the .msmtprc file has correct permissions
          chmod 600 ~/.msmtprc  # Make the file readable and writable only by the user

          # Send the email
          echo -e "Subject: $SUBJECT\n\n$BODY" | msmtp $TO_EMAIL
