name: Website Uptime Monitor

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs 5 every minute
  workflow_dispatch: null

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # This step checks out your repository so you can access files.

      - name: Read URL from file
        id: read_url
        run: |
          # Read the URL from the 'url.txt' file stored in the repository
          URL=$(cat url.txt)
          echo "URL=$URL" >> $GITHUB_ENV  # Set URL as an environment variable to use in subsequent steps

      - name: Check uptime of the URL
        id: uptime_check
        run: |
          # Use curl to check the status code of the website
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" $URL)

          # Save the status code as an output variable for this step
          echo "::set-output name=status_code::$STATUS_CODE"
          
      - name: Send Email Report
        if: steps.uptime_check.outputs.status_code != '200'  # Send email only when the status code is not 200
        run: |
          # Install msmtp to send email via Gmail SMTP
          sudo apt-get install -y msmtp

          # Set Gmail credentials from GitHub secrets
          GMAIL_USERNAME="${{ secrets.GMAIL_USERNAME }}"
          GMAIL_PASSWORD="${{ secrets.GMAIL_PASSWORD }}"
          TO_EMAIL="ktharun4456@gmail.com" # Replace with your recipient's email address  
          SUBJECT="Website Uptime Report"

          # Get the status code from the previous step
          STATUS_CODE=${{ steps.uptime_check.outputs.status_code }}


          # Determine the message body based on the website status
          if [ "$STATUS_CODE" != "200" ]; then
          BODY="The website $URL is DOWN. Status code: $STATUS_CODE."
          fi

          # Configure msmtp to send the email via Gmail SMTP
          echo "account default" > ~/.msmtprc
          echo "host smtp.gmail.com" >> ~/.msmtprc
          echo "port 587" >> ~/.msmtprc
          echo "from $GMAIL_USERNAME" >> ~/.msmtprc
          echo "auth on" >> ~/.msmtprc
          echo "user $GMAIL_USERNAME" >> ~/.msmtprc
          echo "password $GMAIL_PASSWORD" >> ~/.msmtprc
          echo "tls on" >> ~/.msmtprc
          echo "tls_starttls on" >> ~/.msmtprc
          echo "logfile ~/.msmtp.log" >> ~/.msmtprc

          # Ensure the .msmtprc file has correct permissions
          chmod 600 ~/.msmtprc  # Make the file readable and writable only by the user

          # Send the email
          echo -e "Subject: $SUBJECT\n\n$BODY" | msmtp $TO_EMAIL

